### ISSUE TITLE
After Alfred 3 update, I cannot enter login and enter my API token.

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/alfred-toggl#18] opened 2016-05-10 19:36 UTC
Here is the prompt that I get when I enter the 'toggl' workflow :
![2016-05-10 at 21 34](https://cloud.githubusercontent.com/assets/6391776/15159846/ecbae35c-16f6-11e6-95f3-bda0a4ea54f7.png)

If I enter my API token like so :
![2016-05-10 at 21 34](https://cloud.githubusercontent.com/assets/6391776/15159859/06a0b54e-16f7-11e6-8633-870de5672c8b.png)

I am given no option to do anything with it. And when I press here : 

![2016-05-10 at 21 35](https://cloud.githubusercontent.com/assets/6391776/15159879/215d96ea-16f7-11e6-8337-5abf715e803c.png)

I get this error : 

![2016-05-10 at 21 37](https://cloud.githubusercontent.com/assets/6391776/15159935/70bef2b0-16f7-11e6-9905-622cd21270e7.png)

Is there anything I can do about it as I would really like to have this workflow working.

**Comment by jason0x43** [comment] 2016-05-11 03:05
Select the `login` option and press Enter.

**Comment by nikivdev** [comment] 2016-05-11 06:40
I get the same notification error : 

![2016-05-11 at 08 40](https://cloud.githubusercontent.com/assets/6391776/15172117/07c8b75c-1754-11e6-8080-749a6945baf2.png)

**Comment by jason0x43** [comment] 2016-05-11 15:33
Try opening Alfred's debug panel for the Toggl workflow and then activate the tgl 'login' item. What output do you see? (Check over the output and remove any personally identifying information before posting anything here.)

**Comment by nikivdev** [comment] 2016-05-11 17:39
here it is (I just blurred out my username, not sure if there is anything personal in there that I didn't remove) : 

![2016-05-11 at 19 36](https://cloud.githubusercontent.com/assets/6391776/15190385/e7f620e8-17af-11e6-89c2-ad964610cf48.png)

and here it is in text : 

`
[2016-05-11 19:36:29][STDERR: input.scriptfilter] 2016/05/11 19:36:28 Using config file /Users/USER/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2016/05/11 19:36:28 Using cache file /Users/USER/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2016/05/11 19:36:28 Error loading config: open /Users/USER/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json: no such file or directory
2016/05/11 19:36:28 loaded config: { false 0 false}
2016/05/11 19:36:28 loaded cache
[alfred] 2016/05/11 19:36:28 args: []string{"./alfred-toggl", "tell", ""}
[alfred] 2016/05/11 19:36:28 op: 'tell'
[alfred] 2016/05/11 19:36:28 keyword: ''
[alfred] 2016/05/11 19:36:28 query: ''
[alfred] 2016/05/11 19:36:28 prefix: ' '
[alfred] 2016/05/11 19:36:28 skip: 'map[]'
[alfred] 2016/05/11 19:36:28 sorting by keyword:
[2016-05-11 19:36:30][ERROR: action.script] 2016/05/11 19:36:30 Using config file /Users/USER/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2016/05/11 19:36:30 Using cache file /Users/USER/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2016/05/11 19:36:30 Error loading config: open /Users/USER/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json: no such file or directory
2016/05/11 19:36:30 loaded config: { false 0 false}
2016/05/11 19:36:30 loaded cache
[alfred] 2016/05/11 19:36:30 args: []string{"./alfred-toggl", "do", "login"}
[alfred] 2016/05/11 19:36:30 op: 'do'
[alfred] 2016/05/11 19:36:30 keyword: 'login'
[alfred] 2016/05/11 19:36:30 query: ''
[alfred] 2016/05/11 19:36:30 prefix: 'login '
[alfred] 2016/05/11 19:36:30 skip: 'map[]'
[alfred] 2016/05/11 19:36:30 got response: '33:41: execution error: Can’t get application "Alfred 2". (-1728)'
`

**Comment by jason0x43** [comment] 2016-05-11 17:43
Oooooh, I see. Sorry, somehow the part about "Alfred 3" update hadn't sunk in. I haven't tried the workflow with Alfred 3 yet (no beta invite), and apparently there's an issue. It doesn't look anything too significant, but it's difficult to know without Alfred 3 to test with.

**Comment by jason0x43** [comment] 2016-05-18 02:55
Yay, I have Alfred 3 now, so I can finally take a look at this

**Comment by shrop** [comment] 2016-05-18 16:52
thanks @jason0x43!

**Comment by roelvan** [comment] 2016-05-28 09:35
I have the same issue. **Alfred 3**

**Comment by davidacreates** [comment] 2016-06-03 18:07
I have the same issue. Any update?

**Comment by daniel-schulz-codes** [comment] 2016-06-05 19:33
+1

**Comment by jason0x43** [comment] 2016-06-06 13:19
Sorry for the delay, just got back from vacation. This one threw me for a bit because everything seemed fine at first, but I didn't remove Alfred 2 immediately after upgrading to Alfred 3. The issue is that the login process involves some dialog creation, and the dialogs are owned by the Alfred application. Currently, the AppleScript that creates the dialogs assumes the app is "Alfred 2", but now it's "Alfred 3", so I just need to add some logic to check which one is available.

**Comment by jason0x43** [comment] 2016-06-07 02:51
This is fixed in v1.1.7.

**Closed as completed by jason0x43** 2016-06-07 02:51 UTC

**Comment by pugson** [comment] 2016-06-07 16:09
Works great. Thanks @jason0x43! 🙌

**Comment by shrop** [comment] 2016-06-09 12:47
Thank you, @jason0x43! Tested and works great :)
